### ISSUE TITLE
db:setup breaks

### ISSUE THREAD

**Issue by mariokostelac** [eagletmt/switch_point#13]
Migrations are not aware of switch point. Is there any way to change this?

**Comment by eagletmt** [comment]
Basically, Rails' migration tasks are not aware of multiple databases.
There's no easy way to integrate with Rails' migrations and no plan to support it, sorry.

You can retrieve the database.yml entry name for each defined switch points.
Calling `ActiveRecord::Base.establish_connection(SwitchPoint.config.database_name(name, :writable))` before running migrations might help.

**Comment by mariokostelac** [comment]
Seems reasonable. Thanks!
